### ISSUE TITLE
Running this project on Debian throws an error during install

### ISSUE THREAD

**Issue by danielw97** [nahuhh/basicswap-bash#1]
Hi,
I'm attempting to run this project on Debian Bookworm, however receive the following errors during install immediately after python dependancys are installed by the script:
 /usr/local/bin/bsx/setup.sh: line 39: syntax error near unexpected token `['    
 /usr/local/bin/bsx/setup.sh: line 39: `enable_tor() ['                          
 If there's an alternative platform you would prefer this issue be raised on please let me know, although I wanted to make a note of my experience.

**Comment by nahuhh** [comment]
@danielw97 
Please try deleting the ~/coinswaps folder, and running the installer again. just pushed a fix

`bash -c "$(curl -fsSL https://raw.githubusercontent.com/nahuhh/basicswap-bash/beta/scriptinstall.sh)"`

**Comment by danielw97** [comment]
Hi, thanks for getting to this so quickly. Unfortunately, I'm now getting the following error, it looks as though the file isn't downloading correctly immediately after the script is run. Not sure if it is still uploading?
tar: This does not look like a tar archive                                      
                                                                                 
 gzip: stdin: not in gzip format                                                 
 tar: Child returned status 1                                                    
 tar: Error is not recoverable: exiting now                                      
 bash: line 5: cd: basicswap-beta: No such file or directory                     
 bash: line 7: ./install.sh: No such file or directory

**Comment by nahuhh** [comment]
youre right. give it a moment. I think its just slow to update githubs cache

**Comment by nahuhh** [comment]
@danielw97  ok should be good

**Comment by danielw97** [comment]
Excellent, that seems to have fixed it andd I was able to install without issue. Thanks for the quick fix.
